name: Publish Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  
  # Triggered by ODM build (after docker push)
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        variant:
          - dockerfile: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            tag: latest
          - dockerfile: ./Dockerfile.gpu
            platforms: linux/amd64
            tag: gpu
          - dockerfile: ./Dockerfile.gpu.intel
            platforms: linux/amd64
            tags: gpu.intel
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Use the repository information of the checked-out code to format docker tags
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.actor }}/${{ github.repository }}
            opendronemap/nodeodm
          # semver tag is only generated for the cpu version
          tags: |
            ${{ matrix.variant.tag == 'latest' && 'type=semver,pattern={{version}}' }}
            type=raw,value=${{ matrix.variant.tag }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.variant.dockerfile }}
          platforms: ${{ matrix.variant.platforms }}
          push: true
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}